print('Tipo int', '=>', type(1))
print('Tipo decimal', '=>', type(1.0))
print('Tipo string', '=>', type('test'))
print('Tipo bool', '=>', type(True))
print('Tipo bool', '=>', type(False))
print('Tipo list', '=>', type([1, 2, 3]))
